#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DBIx-Class
Version  : 0.082842
Release  : 25
URL      : https://cpan.metacpan.org/authors/id/R/RI/RIBASUSHI/DBIx-Class-0.082842.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RI/RIBASUSHI/DBIx-Class-0.082842.tar.gz
Summary  : 'Extensible and flexible object <-> relational mapper.'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-DBIx-Class-bin = %{version}-%{release}
Requires: perl-DBIx-Class-license = %{version}-%{release}
Requires: perl-DBIx-Class-man = %{version}-%{release}
Requires: perl-DBIx-Class-perl = %{version}-%{release}
Requires: perl(JSON::Any)
Requires: perl(MooseX::Types)
Requires: perl(MooseX::Types::JSON)
Requires: perl(MooseX::Types::LoadableClass)
Requires: perl(MooseX::Types::Path::Class)
Requires: perl(SQL::Abstract::Util)
BuildRequires : buildreq-cpan
BuildRequires : perl(Class::Accessor::Grouped)
BuildRequires : perl(Class::Inspector)
BuildRequires : perl(Config::Any)
BuildRequires : perl(Context::Preserve)
BuildRequires : perl(DBD::SQLite)
BuildRequires : perl(DBI)
BuildRequires : perl(Data::Dumper::Concise)
BuildRequires : perl(Devel::GlobalDestruction)
BuildRequires : perl(Hash::Merge)
BuildRequires : perl(JSON::Any)
BuildRequires : perl(MRO::Compat)
BuildRequires : perl(Module::Find)
BuildRequires : perl(Moo)
BuildRequires : perl(MooseX::Types)
BuildRequires : perl(MooseX::Types::JSON)
BuildRequires : perl(MooseX::Types::LoadableClass)
BuildRequires : perl(MooseX::Types::Path::Class)
BuildRequires : perl(Package::Stash)
BuildRequires : perl(Path::Class)
BuildRequires : perl(SQL::Abstract::Classic)
BuildRequires : perl(Scope::Guard)
BuildRequires : perl(Sub::Name)
BuildRequires : perl(Test::Deep)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Test::Warn)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(namespace::clean)
BuildRequires : perl-Class-C3-Componentised
BuildRequires : perl-DBD-SQLite

%description
See AUTHORS and LICENSE included with this distribution. All rights reserved.
NAME
DBIx::Class - Extensible and flexible object <-> relational mapper.

%package bin
Summary: bin components for the perl-DBIx-Class package.
Group: Binaries
Requires: perl-DBIx-Class-license = %{version}-%{release}

%description bin
bin components for the perl-DBIx-Class package.


%package dev
Summary: dev components for the perl-DBIx-Class package.
Group: Development
Requires: perl-DBIx-Class-bin = %{version}-%{release}
Provides: perl-DBIx-Class-devel = %{version}-%{release}
Requires: perl-DBIx-Class = %{version}-%{release}

%description dev
dev components for the perl-DBIx-Class package.


%package license
Summary: license components for the perl-DBIx-Class package.
Group: Default

%description license
license components for the perl-DBIx-Class package.


%package man
Summary: man components for the perl-DBIx-Class package.
Group: Default

%description man
man components for the perl-DBIx-Class package.


%package perl
Summary: perl components for the perl-DBIx-Class package.
Group: Default
Requires: perl-DBIx-Class = %{version}-%{release}

%description perl
perl components for the perl-DBIx-Class package.


%prep
%setup -q -n DBIx-Class-0.082842
cd %{_builddir}/DBIx-Class-0.082842

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-DBIx-Class
cp %{_builddir}/DBIx-Class-0.082842/LICENSE %{buildroot}/usr/share/package-licenses/perl-DBIx-Class/9a1990499bf1c624338a96288466ea679b285b34
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dbicadmin

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DBIx::Class.3
/usr/share/man/man3/DBIx::Class::AccessorGroup.3
/usr/share/man/man3/DBIx::Class::Admin.3
/usr/share/man/man3/DBIx::Class::CDBICompat.3
/usr/share/man/man3/DBIx::Class::CDBICompat::AbstractSearch.3
/usr/share/man/man3/DBIx::Class::CDBICompat::ColumnsAsHash.3
/usr/share/man/man3/DBIx::Class::CDBICompat::Copy.3
/usr/share/man/man3/DBIx::Class::CDBICompat::Iterator.3
/usr/share/man/man3/DBIx::Class::CDBICompat::NoObjectIndex.3
/usr/share/man/man3/DBIx::Class::CDBICompat::Relationship.3
/usr/share/man/man3/DBIx::Class::CDBICompat::Relationships.3
/usr/share/man/man3/DBIx::Class::CDBICompat::SQLTransformer.3
/usr/share/man/man3/DBIx::Class::Carp.3
/usr/share/man/man3/DBIx::Class::Core.3
/usr/share/man/man3/DBIx::Class::Cursor.3
/usr/share/man/man3/DBIx::Class::DB.3
/usr/share/man/man3/DBIx::Class::Exception.3
/usr/share/man/man3/DBIx::Class::FilterColumn.3
/usr/share/man/man3/DBIx::Class::InflateColumn.3
/usr/share/man/man3/DBIx::Class::InflateColumn::DateTime.3
/usr/share/man/man3/DBIx::Class::InflateColumn::File.3
/usr/share/man/man3/DBIx::Class::Manual.3
/usr/share/man/man3/DBIx::Class::Manual::Component.3
/usr/share/man/man3/DBIx::Class::Manual::Cookbook.3
/usr/share/man/man3/DBIx::Class::Manual::DocMap.3
/usr/share/man/man3/DBIx::Class::Manual::Example.3
/usr/share/man/man3/DBIx::Class::Manual::FAQ.3
/usr/share/man/man3/DBIx::Class::Manual::Features.3
/usr/share/man/man3/DBIx::Class::Manual::Glossary.3
/usr/share/man/man3/DBIx::Class::Manual::Intro.3
/usr/share/man/man3/DBIx::Class::Manual::Joining.3
/usr/share/man/man3/DBIx::Class::Manual::QuickStart.3
/usr/share/man/man3/DBIx::Class::Manual::Reading.3
/usr/share/man/man3/DBIx::Class::Manual::ResultClass.3
/usr/share/man/man3/DBIx::Class::Manual::Troubleshooting.3
/usr/share/man/man3/DBIx::Class::Optional::Dependencies.3
/usr/share/man/man3/DBIx::Class::Ordered.3
/usr/share/man/man3/DBIx::Class::PK.3
/usr/share/man/man3/DBIx::Class::PK::Auto.3
/usr/share/man/man3/DBIx::Class::PK::Auto::DB2.3
/usr/share/man/man3/DBIx::Class::PK::Auto::MSSQL.3
/usr/share/man/man3/DBIx::Class::PK::Auto::MySQL.3
/usr/share/man/man3/DBIx::Class::PK::Auto::Oracle.3
/usr/share/man/man3/DBIx::Class::PK::Auto::Pg.3
/usr/share/man/man3/DBIx::Class::PK::Auto::SQLite.3
/usr/share/man/man3/DBIx::Class::Relationship.3
/usr/share/man/man3/DBIx::Class::Relationship::Base.3
/usr/share/man/man3/DBIx::Class::ResultClass::HashRefInflator.3
/usr/share/man/man3/DBIx::Class::ResultSet.3
/usr/share/man/man3/DBIx::Class::ResultSet::Pager.3
/usr/share/man/man3/DBIx::Class::ResultSetColumn.3
/usr/share/man/man3/DBIx::Class::ResultSetManager.3
/usr/share/man/man3/DBIx::Class::ResultSource.3
/usr/share/man/man3/DBIx::Class::ResultSource::Table.3
/usr/share/man/man3/DBIx::Class::ResultSource::View.3
/usr/share/man/man3/DBIx::Class::ResultSourceHandle.3
/usr/share/man/man3/DBIx::Class::ResultSourceProxy::Table.3
/usr/share/man/man3/DBIx::Class::Row.3
/usr/share/man/man3/DBIx::Class::SQLMaker.3
/usr/share/man/man3/DBIx::Class::SQLMaker::ClassicExtensions.3
/usr/share/man/man3/DBIx::Class::SQLMaker::LimitDialects.3
/usr/share/man/man3/DBIx::Class::SQLMaker::OracleJoins.3
/usr/share/man/man3/DBIx::Class::Schema.3
/usr/share/man/man3/DBIx::Class::Schema::Versioned.3
/usr/share/man/man3/DBIx::Class::Serialize::Storable.3
/usr/share/man/man3/DBIx::Class::StartupCheck.3
/usr/share/man/man3/DBIx::Class::Storage.3
/usr/share/man/man3/DBIx::Class::Storage::BlockRunner.3
/usr/share/man/man3/DBIx::Class::Storage::DBI.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ACCESS.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ADO.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ADO::MS_Jet.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ADO::MS_Jet::Cursor.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ADO::Microsoft_SQL_Server.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ADO::Microsoft_SQL_Server::Cursor.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::AutoCast.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Cursor.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::DB2.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Firebird.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Firebird::Common.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::IdentityInsert.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Informix.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::InterBase.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::MSSQL.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::NoBindVars.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ODBC.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ODBC::ACCESS.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ODBC::DB2_400_SQL.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ODBC::Firebird.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ODBC::Microsoft_SQL_Server.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::ODBC::SQL_Anywhere.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Oracle.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Oracle::Generic.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Oracle::WhereJoins.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Pg.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated::Balancer.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated::Balancer::First.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated::Balancer::Random.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated::Introduction.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated::Pool.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated::Replicant.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Replicated::WithDSN.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::SQLAnywhere.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::SQLAnywhere::Cursor.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::SQLite.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Sybase.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Sybase::ASE.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Sybase::ASE::NoBindVars.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Sybase::FreeTDS.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Sybase::MSSQL.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Sybase::Microsoft_SQL_Server.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::Sybase::Microsoft_SQL_Server::NoBindVars.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::UniqueIdentifier.3
/usr/share/man/man3/DBIx::Class::Storage::DBI::mysql.3
/usr/share/man/man3/DBIx::Class::Storage::Debug::PrettyTrace.3
/usr/share/man/man3/DBIx::Class::Storage::Statistics.3
/usr/share/man/man3/DBIx::Class::Storage::TxnScopeGuard.3
/usr/share/man/man3/DBIx::Class::UTF8Columns.3
/usr/share/man/man3/SQL::Translator::Parser::DBIx::Class.3
/usr/share/man/man3/SQL::Translator::Producer::DBIx::Class::File.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-DBIx-Class/9a1990499bf1c624338a96288466ea679b285b34

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dbicadmin.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
